project_id = "fbifazlicxbyhryzozbe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.calculate-geotechnical-parameters]
verify_jwt = true

[functions.compute-spt]
verify_jwt = true

[functions.compute-cpt]
verify_jwt = true

[functions.compute-atterberg]
verify_jwt = true

[functions.compute-psd]
verify_jwt = true

[functions.compute-cbr]
verify_jwt = true